### ISSUE TITLE
Bakgrunnsfarge?

### ISSUE THREAD

**Issue by Thyrgils** [Gruppe-7B/iTer#20]
Hvilken bakgrunnsfarge skal vi ha? Skal vi bare ha "standard" hvit eller skal vi finne eller litt mer fancy og øko-trendy bakgrunnsfarge?

**Comment by kristervv** [comment]
Hei @Thyrgils, kjempebra innlegg! Litt usikker selv, looper inn @gsvartsund siden han vet litt mer enn meg

**Comment by Thyrgils** [comment]
Hei @gsvartsund og @kristervv ! Knallbra forslag! Den er kjempefin. Jeg synes at vi skal gå for det!
